import { FormEvent, useMemo, useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, Circle, Plus, X } from "lucide-react";
import { NewTrailer, Trailer } from "./trailer.types";
import { formatOperationalDate, shiftOperationalDate, toOperationalDate } from "./trailer.utils";

type Props = {
  trailers: Trailer[];
  onUpdate: (id: number, patch: Partial<Trailer>) => void;
  onCreate: (trailer: NewTrailer) => void;
};

export function AdminPlanning({ trailers, onUpdate, onCreate }: Props) {
  const today = toOperationalDate();
  const [selectedDate, setSelectedDate] = useState(today);
  const [showAddForm, setShowAddForm] = useState(false);
  const [selectedTrailerId, setSelectedTrailerId] = useState<number>();
  const selectedTrailers = useMemo(() => trailers.filter(trailer => trailer.date === selectedDate).sort((a, b) => a.bookedTime.localeCompare(b.bookedTime)), [trailers, selectedDate]);
  const selectedTrailer = trailers.find(trailer => trailer.id === selectedTrailerId);

  return <section className="planningSection"><div className="sectionHead"><div><h2>Admin planning</h2><p>Create and edit trailer plans by operational date.</p></div><button className="primary compact" onClick={() => setShowAddForm(true)}><Plus size={17}/>Add trailer</button></div>
    <div className="dateNavigator"><button className="dateArrow" onClick={() => setSelectedDate(current => shiftOperationalDate(current, -1))} aria-label="Previous day"><ChevronLeft/></button><div className="selectedDate"><b>{formatOperationalDate(selectedDate)}</b><input aria-label="Select planning date" type="date" value={selectedDate} onChange={event => setSelectedDate(event.target.value || today)}/></div><button className="dateArrow" onClick={() => setSelectedDate(current => shiftOperationalDate(current, 1))} aria-label="Next day"><ChevronRight/></button><button className="todayBtn" disabled={selectedDate === today} onClick={() => setSelectedDate(today)}>Today</button></div>
    {showAddForm && <AddTrailerForm selectedDate={selectedDate} onCancel={() => setShowAddForm(false)} onCreate={trailer => { onCreate(trailer); setShowAddForm(false) }}/>} 
    <div className="adminPanel"><div className="planSummary"><b>{selectedTrailers.length} {selectedTrailers.length === 1 ? "trailer" : "trailers"}</b><span>Plan for {formatOperationalDate(selectedDate)}</span></div>{selectedTrailers.length ? <div className="adminTableWrap"><table><thead><tr><th>Trailer / load number</th><th>Booked</th><th>Carrier</th><th>Planned pallets</th><th>Status</th><th></th></tr></thead><tbody>{selectedTrailers.map(trailer => <tr key={trailer.id}><td><input aria-label={`Trailer ${trailer.id} load number`} value={trailer.loadNumber} onChange={event => onUpdate(trailer.id, { loadNumber: event.target.value })}/></td><td><input aria-label={`Trailer ${trailer.id} booked time`} type="time" value={trailer.bookedTime} onChange={event => onUpdate(trailer.id, { bookedTime: event.target.value })}/></td><td><input aria-label={`Trailer ${trailer.id} carrier`} value={trailer.carrier} onChange={event => onUpdate(trailer.id, { carrier: event.target.value })}/></td><td><input aria-label={`Trailer ${trailer.id} planned pallets`} type="number" min="0" value={trailer.plannedPallets} onChange={event => onUpdate(trailer.id, { plannedPallets: Number(event.target.value) })}/></td><td><span className={`status ${trailer.status.toLowerCase()}`}>{trailer.status.replace("_", " ")}</span></td><td><button className="rowDetailsBtn" onClick={() => setSelectedTrailerId(trailer.id)}>View</button></td></tr>)}</tbody></table></div> : <div className="emptyDay"><h3>No trailers planned</h3><p>Add a trailer to prepare this date’s plan.</p></div>}</div>{selectedTrailer && <TrailerDetails trailer={selectedTrailer} onUpdate={onUpdate} onClose={() => setSelectedTrailerId(undefined)}/>} 
  </section>;
}

function TrailerDetails({ trailer, onUpdate, onClose }: { trailer: Trailer; onUpdate: (id: number, patch: Partial<Trailer>) => void; onClose: () => void }) {
  const variance = trailer.actualPallets === undefined ? undefined : trailer.actualPallets - trailer.plannedPallets;
  const reached = (step: "BOOKED" | "LOADED" | "LEFT_SITE") => ["BOOKED", "LOADED", "LEFT_SITE"].indexOf(trailer.status) >= ["BOOKED", "LOADED", "LEFT_SITE"].indexOf(step);
  return <div className="detailsBackdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="reportDetails trailerDetails" role="dialog" aria-modal="true" aria-labelledby="trailer-details-title"><div className="formTitle"><div><span className="eyebrow">{formatOperationalDate(trailer.date)}</span><h2 id="trailer-details-title">Load {trailer.loadNumber}</h2><p>{trailer.carrier} · {trailer.bookedTime}</p></div><button className="closeBtn" onClick={onClose} aria-label="Close trailer details"><X size={22}/></button></div><span className={`status ${trailer.status.toLowerCase()}`}>{trailer.status.replace("_", " ")}</span><dl className="reportMeta"><div><dt>Date</dt><dd>{trailer.date}</dd></div><div><dt>Booked time</dt><dd>{trailer.bookedTime}</dd></div><div><dt>Carrier</dt><dd>{trailer.carrier}</dd></div><div><dt>Door</dt><dd>{trailer.door ?? "—"}</dd></div><div><dt>Planned pallets</dt><dd>{trailer.plannedPallets}</dd></div><div><dt>Actual pallets</dt><dd>{trailer.actualPallets ?? "—"}</dd></div><div><dt>Variance</dt><dd className={variance ? "varianceText" : ""}>{variance === undefined ? "—" : variance === 0 ? "No variance" : `${variance > 0 ? "+" : ""}${variance}`}</dd></div><div><dt>Current status</dt><dd>{trailer.status === "LOADED" ? "LOADED · Ready for collection" : trailer.status === "LEFT_SITE" ? "LEFT SITE · Physically departed" : "BOOKED"}</dd></div></dl><label className="driverInEdit">Driver In time <span className="optional">Optional</span><input type="time" value={trailer.driverInAt ?? ""} onChange={event => onUpdate(trailer.id, { driverInAt: event.target.value || undefined })}/></label><div className="lifecycle"><h3>Core lifecycle</h3><div>{(["BOOKED", "LOADED", "LEFT_SITE"] as const).map(step => <div className={reached(step) ? "lifecycleStep complete" : "lifecycleStep"} key={step}>{reached(step) ? <CheckCircle2 size={19}/> : <Circle size={19}/>}<b>{step.replace("_", " ")}</b>{step === "LOADED" && trailer.loadedAt && <span>{trailer.loadedAt}</span>}{step === "LEFT_SITE" && trailer.leftSiteAt && <span>{trailer.leftSiteAt}</span>}</div>)}</div></div><dl className="actionTimes"><div><dt>Driver In (optional)</dt><dd>{trailer.driverInAt ?? "—"}{trailer.driverInBy ? ` by ${trailer.driverInBy}` : ""}</dd></div><div><dt>Loaded / ready</dt><dd>{trailer.loadedAt ?? "—"}{trailer.loadedBy ? ` by ${trailer.loadedBy}` : ""}</dd></div><div><dt>Left Site</dt><dd>{trailer.leftSiteAt ?? "—"}{trailer.leftSiteBy ? ` by ${trailer.leftSiteBy}` : ""}</dd></div></dl></section></div>;
}

function AddTrailerForm({ selectedDate, onCancel, onCreate }: { selectedDate: string; onCancel: () => void; onCreate: (trailer: NewTrailer) => void }) {
  const [bookedTime, setBookedTime] = useState(""); const [loadNumber, setLoadNumber] = useState(""); const [carrier, setCarrier] = useState(""); const [plannedPallets, setPlannedPallets] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); const pallets = Number(plannedPallets); if (!bookedTime || !loadNumber.trim() || !carrier.trim() || !Number.isFinite(pallets) || pallets < 0) return; onCreate({ date: selectedDate, bookedTime, loadNumber: loadNumber.trim(), carrier: carrier.trim(), plannedPallets: pallets }) };
  return <div className="addTrailerPanel"><div className="formTitle"><div><span className="eyebrow">{formatOperationalDate(selectedDate)}</span><h3>Add trailer</h3></div><button className="closeBtn" onClick={onCancel} aria-label="Close add trailer form"><X size={21}/></button></div><form className="trailerPlanForm" onSubmit={submit}><label>Booked time<input required type="time" value={bookedTime} onChange={event => setBookedTime(event.target.value)}/></label><label>Trailer / load number<input required value={loadNumber} onChange={event => setLoadNumber(event.target.value)} placeholder="e.g. LD-104"/></label><label>Carrier<input required value={carrier} onChange={event => setCarrier(event.target.value)} placeholder="Carrier name"/></label><label>Planned pallets<input required type="number" min="0" inputMode="numeric" value={plannedPallets} onChange={event => setPlannedPallets(event.target.value)}/></label><div className="formActions"><button type="button" className="secondaryBtn" onClick={onCancel}>Cancel</button><button className="primary compact" disabled={!bookedTime || !loadNumber.trim() || !carrier.trim() || plannedPallets === ""}><Plus size={17}/>Add to plan</button></div></form></div>;
}
